---
swagger: '2.0'
info:
  version: 1.0.0
  title: VPNGen /// Partner API 
basePath: /
paths:
  /admin:
    post:
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        201:
          description: VPN Admin config.
          schema:
              $ref: "#/definitions/admin"
        403: 
          description: 'You do not have necessary permissions for the resource'
        429:
          description: 'Rate limit reached for requests'
        default:
          description: error
          schema:
              $ref: "#/definitions/error"
  /v2/admin:
    post:
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        201:
          description: New user created.
          schema:
            $ref: "#/definitions/newadmin"
        403: 
          description: 'You do not have necessary permissions for the resource'
        500:
          description: 'Internal server error'
        default:
          description: error
          schema:
              $ref: "#/definitions/error"
  /longping:
    post:
      produces:
        - application/json
      responses:
        200:
          description: Longping
          schema:
            type: object
            properties:
              message:
                type: string
                example: "pong"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  admin:
    type: object
    required:
      - UserName
      - SeedMnemo
      - WireGuardConfig
      - WireGuardConfigName
      - KeydeskIPv6Address
      - PersonName
      - PersonDesc
      - PersonDescLink
    properties:
      UserName:
        type: string
      SeedMnemo:
        type: string
      WireGuardConfig:
        type: string
      WireGuardConfigName:
        type: string
      KeydeskIPv6Address:
        type: string
      PersonName:
        type: string
      PersonDesc:
        type: string
      PersonDescLink:
        type: string
  newadmin:
    type: object
    required:
      - Name # UserName without number
      - Mnemo
      - Configs
      - KeydeskIPv6
      - Person
    properties:
      Name:
        type: string
      Mnemo:
        type: string
      Configs:
        $ref: "#/definitions/newuser"
      KeydeskIPv6:
        type: string
      Person:
        $ref: "#/definitions/person"
  newuser:
    type: object
    required:
      - UserName
    properties:
      UserName:
        type: string
      WireguardConfig:
        type: object
        required:
          - TonnelName
          - FileName
          - FileContent
        properties:
          TonnelName:
            type: string
          FileName:
            type: string
          FileContent:
            type: string      
      AmnzOvcConfig:
        type: object
        required:
          - TonnelName
          - FileName
          - FileContent
        properties:
          TonnelName:
            type: string
          FileName:
            type: string
          FileContent:
            type: string
      IPSecL2TPManualConfig:
        type: object
        required:
          - Server
          - PSK
          - Username
          - Password
        properties:
          Server:
            type: string
          PSK:
            type: string
          Username:
            type: string
          Password:
            type: string
      OutlineConfig:
        type: object
        required:
          - AccessKey
        properties:
          AccessKey:
            type: string
  person:
    type: object
    required:
      - Name
      - Desc
      - Gender
      - URL
    properties:
      Name:
        type: string
      Desc:
        type: string
      Gender:
        type: integer
        format: int32
      URL:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
      message:
        type: string
        
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
